---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>
  elevated: true
  elevated_username: <%= ENV["machine_user"] %>
  elevated_password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012R2
    driver_config:
      communicator: winrm
    transport:
      name: winrm

suites:
  - name: tasks
    run_list:
      - recipe[visualstudio::default]
    attributes: {
      'visualstudio': {
        'version': '2015',
        'edition': 'community',
        'source': 'https://download.microsoft.com/download/0/B/C/0BC321A4-013F-479C-84E6-4A2F90B11269/',
        'preserve_extracted_files': true
      }
    }
