version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

environment:
  winrm_user: test_user
  winrm_pass: Pass@word1
  winrm_port: 5985
  KITCHEN_YAML: c:\projects\visualstudio\.kitchen.appveyor.yml

  matrix:
    - ruby_version: "21"

clone_folder: c:\projects\visualstudio
clone_depth: 1
branches:
  only:
    - master

install:
  - ps: net user /add $env:winrm_user $env:winrm_pass
  - ps: net localgroup administrators $env:winrm_user /add
  - ps: New-Object System.Net.WebClient).DownloadFile('https://packages.chef.io/stable/windows/2008r2/chefdk-0.17.17-1-x86.msi', 'c:\projects\chefdk.msi'
  - ps: msiexec /qb /i c:\projects\chefdk.msi 

test_script:
  - C:\opscode\chefdk\bin\kitchen verify