version: "master-{build}"

# Use the 2013 image so VS 2015 isn't already installed
image: Visual Studio 2013
platform: x64

cache:
  - c:\projects\bundle

environment:
  matrix:
    - ruby_version: "22"

clone_folder: c:\projects\cookbooks\visualstudio
clone_depth: 1

install:
  - ps: Invoke-WebRequest -Uri http://www.getchef.com/chef/install.msi -OutFile c:\projects\chef.msi
  - ps: Invoke-WebRequest -Uri https://packages.chef.io/stable/windows/2008r2/chefdk-0.17.17-1-x86.msi -OutFile c:\projects\chefdk.msi
  - ps: Start-Process C:\Windows\System32\msiexec.exe -ArgumentList "/qb /i c:\projects\chefdk.msi" -wait
  - ps: Start-Process C:\Windows\System32\msiexec.exe -ArgumentList "/qn /i c:\projects\chef.msi" -wait
  - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  - c:\opscode\chefdk\bin\berks vendor c:\projects\cookbooks
  - bundle config --local path c:\projects\bundle
  - bundle install

build_script:
  - bundle exec rake

test_script:
  - c:\opscode\chef\bin\chef-client --local-mode --fatal-windows-admin-check --log_level info -j c:\projects\cookbooks\visualstudio\appveyor-node.json
